### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by s265452** [JeroenDM/elion#11]
Hi everyone, 
I wish to implement your planner.
I followed your instructions:

mkdir -p catkin_ws/src
cd catkin_ws/src
git clone https://github.com/JeroenDM/elion.git
rosdep install --from-paths . --ignore-src

Here that's all right, but when I try to 

vcs import < elion/test_dependencies.repos

I've these problems 

~/catkin_ws/src$ vcs import < elion/test_dependencies.repos
Traceback (most recent call last):
  File "/usr/local/bin/vcs", line 11, in <module>
    load_entry_point('vcstool==0.3.0', 'console_scripts', 'vcs')()
  File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/__init__.py", line 1, in <module>
    from .branch import BranchCommand
  File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/branch.py", line 6, in <module>
    from .command import Command
  File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/command.py", line 6, in <module>
    from vcstool.executor import execute_jobs
  File "/usr/local/lib/python2.7/dist-packages/vcstool/executor.py", line 31
    file=stdout)
        ^
SyntaxError: invalid syntax

Can you help me???

Thank you in advance

**Comment by JeroenDM** [comment]
This seems like an issue with the [vcstool](https://github.com/dirk-thomas/vcstool) installation. What ROS version and operating system are you using?

**Comment by s265452** [comment]
ROS Melodic 18.04
Ubuntu

**Comment by JeroenDM** [comment]
The default version of vcs tools does not support python2 anymore. See https://github.com/dirk-thomas/vcstool/issues/231.
For more info on installing the python2 version see [their readme](https://github.com/dirk-thomas/vcstool#python-27---34-support).

I will close it here as the error is not related to this package.
